### ISSUE TITLE
Option to choose version of the puppet style guide

### ISSUE THREAD

**Issue by bemeyert** [rodjek/puppet-lint#190]
Hi,

It would be very helpful if one could choose the version of the Puppetlabs style guide which should be applied. This would make transitions to new versions much easier.

Thanks, Shorty

**Comment by rnelson0** [comment]
@bemeyert as the style guide is a constantly updated document without versions per se (I don't think commit hashes really counts) I think this is currently not very feasible. If you have a way to make this feasible, please re-open the ticket with some more details. Thanks!

**Comment by ghoneycutt** [comment]
@rnelson0,

The Style Guide is versioned[1]. When I initially wrote it, I made a point to version the document, so that you could say, as @bemeyert suggests, "We comply with Style Guide v1.2.3". Each section is numbered so that you could further explain that you comply with Style Guide v1.2.3 except for section 23.1. With the advent of puppet-lint having a name that corresponds to each part of the section, the numbers are not really used though they are there and are meant to be consistent with the versioning.

As the versioning changes and new checks are added and old checks are modified (think 80char to 140char), some like @bemeyert might find it useful to say that they comply with a specific version of the guide. This could be achieved by having something like '--sgversion=1.2.3' and that would map to a hash of checks and if they are enabled or not.

In practice though, I don't really see this adding much value. You generally go with the lint configuration of a third party module and for your own modules, you use puppet-lint as it is and perhaps add some of your own checks to skip and perhaps even add some extra community written checks. Modules generated[2] using `puppet module generate` even skip parts of the official style guide. 

[1] - https://docs.puppet.com/guides/style_guide.html#metadata
[2] - https://github.com/puppetlabs/puppet/blob/master/lib/puppet/module_tool/skeleton/templates/generator/Rakefile#L10
