### ISSUE TITLE
How to disable some fix ?

### ISSUE THREAD

**Issue by PierreR** [rodjek/puppet-lint#383]
Is there a way to disable some fix  (the same way we disable check) ?

For instance I don't really see the point of this fix:
```
Converting 3 digit octal file modes into 4 digit modes.
```

Does `puppet-lint --fix` take into account the `--no-file_mode-check` ?

As a final note, ideally I would like to keep the `file_mode` check but only disable the `mode should be represented as a 4 digit octal value or symbolic mod` check because I don't see the point of it right now. It looks like the puppetlabs code examples generally don't touch  the suid bit.

**Comment by ghoneycutt** [comment]
The point of that check is that if you only describe the mode with three digits, you are not fully describing a file, which has four digits. Puppet will only manage those three digits and not the forth which leads to configuration drift and likely security issues. Since we are defining state, we want to define the entire state of a given mode, not just the part that you might be familiar with.

http://en.wikipedia.org/wiki/File_system_permissions#Changing_permission_behavior_with_setuid.2C_setgid.2C_and_sticky_bits

**Comment by PierreR** [comment]
My understanding was that puppet will add the extra `0` anyway. So `764` for instance will become `0764` which I thought meant `Puppet is not doing anything fancy with the sticky bit` (which seems a good default case)
 
> Puppet will only manage those three digits and not the forth which leads to configuration drift and > likely security issues. 

Can you confirm that my assumption is wrong. My ruby is rusty and I cannot really figure it out looking at the source:
https://github.com/puppetlabs/puppet/blob/master/lib/puppet/provider/file/posix.rb#L119-L135

**Comment by rodjek** [comment]
@PierreR while I agree with @ghoneycutt here that you should put the leading 0 in your file modes rather than relying on the internal behaviour of Puppet (because being explicit leads to less suprises), you can just disable that check if you don't want to puppet-lint to warn on it (which will also skip automatically fixing it when run with `--fix`). Details on how to do this are available in the [README](https://github.com/rodjek/puppet-lint#disabling-checks).

**Comment by PierreR** [comment]
@rodjek Thanks for mentioning that disabling a check will also skip fixing. I guess I just don't see the line where it is explicitly described in the README.

Also I would have appreciated a more explicit answer ? Is the `--no-file_mode-check` the only flag I can use. This will disable no only the check I am talking about but other potential useful checks about `file_mode` (like rejecting 'zg=rwx,o=r' for a start).
