### ISSUE TITLE
unquoted_node_name false-positives on regexes

### ISSUE THREAD

**Issue by ebroder** [rodjek/puppet-lint#388]
You don't quote node names when they're expressed as regexes (https://docs.puppetlabs.com/puppet/latest/reference/lang_node_definitions.html#regular-expression-names), but puppet-lint flags it as failing the unquoted_node_name check

**Comment by ebroder** [comment]
(It looks like it also false-positives on the un-quoted string `default`, which has special meaning)

**Comment by atrepca** [comment]
Happening here too, fails on a line like below:

`node /my-host-name-[env1|env2|env3]/ inherits base {}`

With:

`WARNING: unquoted node name found on line X`

**Comment by rnelson0** [comment]
Verified this is still present in puppet-lint 2.0.0.

**Comment by rnelson0** [comment]
I believe this is working properly. The sample at https://docs.puppetlabs.com/puppet/latest/reference/lang_node_definitions.html#regular-expression-names does not raise an error. The sample `node /my-host-name-[env1|env2|env3]/ inherits base {}` raises an error because `base` is not quoted; changing it to `'base'` removes the error. Thanks!
