### ISSUE TITLE
puppet-lint --help does not work

### ISSUE THREAD

**Issue by ltutar** [rodjek/puppet-lint#423]
Hi,

I am not able to run puppet-lint --help.

[root@puppetmaster manifests]# puppet-lint --help
puppet-lint: invalid option: --no-class_parameter_defaults-check
puppet-lint: try 'puppet-lint --help' for more information
[root@puppetmaster manifests]#

**Comment by rothsa** [comment]
The --help option is recognized in puppet-lint because puppet-lint's options parser requires 'optparse', and that inheritance is how --help would get recognized. Optparse is a class in Ruby, so there's likely something going on there in your local environment where optparse is not able to be used or loaded correctly.

I'm able to print out the expected results for $puppet-lint --help 
on ruby 2.0.0p481 and a fresh clone from this repository.

**Comment by ltutar** [comment]
Ok. Thank you. I will look for what I am missing.
