### ISSUE TITLE
puppet-lint crashes with "invalid byte sequence in UTF-8 (ArgumentError)"

### ISSUE THREAD

**Issue by mfragkoulis** [rodjek/puppet-lint#458]
On Mac OS X 10.10.5 with Ruby 2.0.0 when running puppet-lint on puppetlabs/puppet

**Comment by rnelson0** [comment]
Some discussion in #459 called out a situation where a selinux policy, which matches the pattern `*.pp`, was caught in the lint file list. If that's the case, I wonder if it would be more appropriate to die with a helpful error message about the encoding, rather than coerce a random coding into utf-8 and try and parse whatever the result is.

**Comment by mfragkoulis** [comment]
IMHO it makes sense and it would have been helpful to me in this specific situation.

**Comment by rodjek** [comment]
Closing this issue now. The specific problem (puppet-lint attempting to parse selinux policy packages) was resolved in #733 and the general solution of reading manifests as UTF-8 was resolved in #730
