### ISSUE TITLE
Empty lines with trailing whitespace triggers redundant soft tabs error.

### ISSUE THREAD

**Issue by james-powis** [rodjek/puppet-lint#478]
Using version 2.0.0 of the gem the manifest on an empty line without spacing equiling the two-space soft tab we get this following:
manifests/jenkins.pp - ERROR: trailing whitespace found on line 34
manifests/jenkins.pp - ERROR: two-space soft tabs not used on line 34

Where as with the two-space soft tab we get:
manifests/jenkins.pp - ERROR: trailing whitespace found on line 34

Where as on version 1.1.0 with 2 space soft-tabs on an empty line produces no errors.

**Comment by dioni21** [comment]
@james-powis you mean a line with only two spaces in it?  IMHO, puppet-lint is now correct, and was wrong before.

Probably your editor is leaving these spaces, but it can surely be configured not to.

**Comment by rnelson0** [comment]
The trailing whitespace error is correct, [that should not be there.](https://docs.puppet.com/guides/style_guide.html#spacing-indentation-and-whitespace)

However, the soft tabs error, while technically correct, is nonsensical, since it's in trailing whitespace. Fixing that remedies the other error, so in this case `soft tabs` should be suppressed.

**Comment by james-powis** [comment]
you are absolutely correct... VIM was failing to remove the whitespace... hitting x did the trick... closing as my stupidity
