### ISSUE TITLE
Puppet-lint crash with new puppet 4 syntax

### ISSUE THREAD

**Issue by jlintz** [rodjek/puppet-lint#516]
Test case:

```
file { 'foo':
  owner   => 'test',
  content => "
    export bar=\"${join(hiera('test'), "," )}\"
  "
}
```

running `puppet-lint test.pp`

Results in

```
/Users/justin/.rbenv/versions/2.1.9/lib/ruby/gems/2.1.0/gems/puppet-lint-2.0.0/lib/puppet-lint/lexer.rb:356:in `interpolate_string': undefined method `[]' for nil:NilClass (NoMethodError)
    from /Users/justin/.rbenv/versions/2.1.9/lib/ruby/gems/2.1.0/gems/puppet-lint-2.0.0/lib/puppet-lint/lexer.rb:183:in `tokenise'
    from /Users/justin/.rbenv/versions/2.1.9/lib/ruby/gems/2.1.0/gems/puppet-lint-2.0.0/lib/puppet-lint/checks.rb:25:in `load_data'
    from /Users/justin/.rbenv/versions/2.1.9/lib/ruby/gems/2.1.0/gems/puppet-lint-2.0.0/lib/puppet-lint/checks.rb:53:in `run'
    from /Users/justin/.rbenv/versions/2.1.9/lib/ruby/gems/2.1.0/gems/puppet-lint-2.0.0/lib/puppet-lint.rb:174:in `run'
    from /Users/justin/.rbenv/versions/2.1.9/lib/ruby/gems/2.1.0/gems/puppet-lint-2.0.0/lib/puppet-lint/bin.rb:59:in `block in run'
    from /Users/justin/.rbenv/versions/2.1.9/lib/ruby/gems/2.1.0/gems/puppet-lint-2.0.0/lib/puppet-lint/bin.rb:56:in `each'
    from /Users/justin/.rbenv/versions/2.1.9/lib/ruby/gems/2.1.0/gems/puppet-lint-2.0.0/lib/puppet-lint/bin.rb:56:in `run'
    from /Users/justin/.rbenv/versions/2.1.9/lib/ruby/gems/2.1.0/gems/puppet-lint-2.0.0/bin/puppet-lint:7:in `<top (required)>'
    from /Users/justin/.rbenv/versions/2.1.9/bin/puppet-lint:23:in `load'
    from /Users/justin/.rbenv/versions/2.1.9/bin/puppet-lint:23:in `<main>'
```

Puppet will properly parse this and execute it with expected behavior

**Comment by jlintz** [comment]
Tracked this down to adding the delimeter parameter to the `join` function will trigger this and when removed it doesn't crash

**Comment by rnelson0** [comment]
It has to do with the double quotes inside the double quoted string. 
```
  content => "
    export bar=\"${join(hiera('test'), "," )}\"
  "
```
This I believe is a strangely allowed format, because of the interpolation of `$(function())`, where you should not place unescaped double quotes within a double quoted string. Changing the delimiter to single quotes eliminates the issue.

**Comment by rnelson0** [comment]
I am not sure how we would properly find that. The first double quote should be the end of the string, after all. If you wanted to figure out a way to account for this, I believe it would involve [`tokenise()`](https://github.com/rodjek/puppet-lint/blob/master/lib/puppet-lint/lexer.rb#L200-L204) and [`interpolate_string()`](https://github.com/rodjek/puppet-lint/blob/master/lib/puppet-lint/lexer.rb#L380-L392). I'm just not sure it SHOULD be done even if it can since it appears to violate expectations of allowed unescaped characters inside of a double quoted string.

**Comment by rnelson0** [comment]
Thanks to Henrik, found the puppet lexer does this with [`slurp_dqstring`](https://github.com/puppetlabs/puppet/blob/a5afe45e8f5d88d23e8f1c114b75f5dafe168d4a/lib/puppet/pops/parser/slurp_support.rb#L32-L43). This might be something to review in the 3.0.0 branch when we can leverage the puppet lexer.

**Comment by markeganfuller** [comment]
Just a side note on temporary workarounds, whilst changing the quotes works fine for some strings if you're trying to insert a line break you need double quotes, in this case you can define it as a variable and use that instead:

```puppet
$join_str = "\n"
postfix::hash { '/etc/postfix/virtual':
  content => "${ $virtual.join($join_str) }\n",
}
```
