### ISSUE TITLE
Fix for variables_not_enclosed incorrectly handles variables followed by a dash

### ISSUE THREAD

**Issue by software-opal** [rodjek/puppet-lint#836]
Having a string like the following is incorrectly fixed when using the `--fix` flag:

Input: `"$hostname-keystore"`
Output: `"${hostname-keystore}"`
Expected: `"${hostname}-keystore"`

**Comment by usev6** [comment]
Huh, this feels a bit tricky. As far as I understand there are two ways to parse ```"$hostname-keystore"```:

Alternative 1)
```
<Token :DQPRE () @1:1>
<Token :UNENC_VARIABLE (hostname) @1:2>
<Token :DQPOST (-keystore) @1:11>
```

Alternative  2)
```
<Token :DQPRE () @1:1>
<Token :UNENC_VARIABLE (hostname-keystore) @1:2>
<Token :DQPOST () @1:20>
```

Currently the second approach is taken. This behaviour is even tested in https://github.com/rodjek/puppet-lint/blob/8a509bc6e4/spec/puppet-lint/plugins/check_variables/variable_contains_dash_spec.rb#L18-L28 : The test expects ```variable_contains_dash``` to complain. But if the parser decides that the token is ```$hostname-keystore``` then it's not sensible to enclose only ```hostname``` in curly braces when fixing for ```variables_not_enclosed```.

In order to parse the code like 1) one could change ```UNENC_VAR_PATTERN``` in ```lib/puppet-lint/lexer/string_slurper.rb``` to *not* include dashes (regex is a slightly adjusted version from https://puppet.com/docs/puppet/6.4/lang_variables.html#variable-names). In this case the code from this issue works as expected. The only failing tests are those linked above (in spec/puppet-lint/plugins/check_variables/variable_contains_dash_spec.rb).
```
diff --git a/lib/puppet-lint/lexer/string_slurper.rb b/lib/puppet-lint/lexer/string_slurper.rb
index 698b472..e918ae5 100644
--- a/lib/puppet-lint/lexer/string_slurper.rb
+++ b/lib/puppet-lint/lexer/string_slurper.rb
@@ -14,7 +14,7 @@ class PuppetLint
       START_INTERP_PATTERN = %r{\$\{}
       END_INTERP_PATTERN = %r{\}}
       END_STRING_PATTERN = %r{(\A|[^\\])(\\\\)*"}
-      UNENC_VAR_PATTERN = %r{(\A|[^\\])\$(::)?(\w+(-\w+)*::)*\w+(-\w+)*}
+      UNENC_VAR_PATTERN = %r{(\A|[^\\])\$(::)?([a-z][a-z0-9_]*::)*[a-z0-9_][a-zA-Z0-9_]*}
       ESC_DQUOTE_PATTERN = %r{\\+"}
       LBRACE_PATTERN = %r{\{}
```

If I'm not mistaken the described ambiguity in parsing does not exist for ```$hostname-keystore``` (no double quotes).
