### ISSUE TITLE
2.5.0 available on rubygems.org but not tagged

### ISSUE THREAD

**Issue by smortex** [rodjek/puppet-lint#953]
According to rubygems, the latest version is 2.5.0:
https://rubygems.org/gems/puppet-lint

However, the source code still refer to 2.4.2.

Somebody forgot to push, or somebody else got control of the gem :unamused:

**Comment by usev6** [comment]
puppet-lint is maintained in the puppetlabs namespace since last week -- see https://github.com/rodjek/puppet-lint/pull/950.

And they made a release 2.5.0: https://github.com/puppetlabs/puppet-lint/releases/tag/v2.5.0

So I think everything is fine.

[Disclaimer: I don't know how such cases are supposed to be handled by rubygems. The link to ```Homepage``` at https://rubygems.org/gems/puppet-lint still points to this repo.]

**Comment by smortex** [comment]
@usev6 good catch!

The metadata seems to be good in the new repo so maybe some caching at rubygem…
